### ISSUE TITLE
No se ven tus cambios

### ISSUE THREAD

**Issue by asanzo** [pdepjm/2021-kata0-prensentacion-pipenani#1]
¡Hola, @pipenani ! ¿Qué pasó con el otro repo que creaste? En este no aparece nada. ¿Te respondieron de Github?

**Comment by felipenani** [comment]
> ¡Hola, @pipenani ! ¿Qué pasó con el otro repo que creaste? En este no aparece nada. ¿Te respondieron de GitHub?

Hola @asanzo , recién te respondo porque entre cumpleaños y covid ayer se me complico. En cuanto al otro usuario, me dice que sigue "flagged" y el support no me respondió. Seguí subiendo y actualizando el repo que dice "-ghost" y cuando termine intente hacer lo mismo pero con este. Hice todos los pasos de manera correcta pero cuando quiero hacer el PUSH en el VS Code me salta el cartelito de abajo que me dice que no estoy autorizado a realizar cambios. No se como podemos continuar. Yo por las dudas deje todo completo en el otro repo.

**Comment by asanzo** [comment]
¡EA! ¿Cuándo cumpliste? ¡Feliz cumpleaños! :cake: :partying_face: :birthday: 
Lo que no entiendo es lo de Covid. ¿Tuviste vos? ¡A cuidarse y a cuidar a quienes uno quiere!

Da de baja pipenani y yafu. Quedate con felipenani. 

Me había olvidado lo de ghost, ahí te corrijo la nota y te comento en el repo.

Saludos!!

**Comment by felipenani** [comment]
> ¡EA! ¿Cuándo cumpliste? ¡Feliz cumpleaños! 🍰 🥳 🎂
> Lo que no entiendo es lo de Covid. ¿Tuviste vos? ¡A cuidarse y a cuidar a quienes uno quiere!
> 
> Da de baja pipenani y yafu. Quedate con felipenani.
> 
> Me había olvidado lo de ghost, ahí te corrijo la nota y te comento en el repo.
> 
> Saludos!!

Jajajaj gracias cumpli ayer, y el covid es mi hermano pero estamos todos juntos jaja. Buenisimo entonces, ya la doy de baja y entonces me quedo con el repo de g host y con esta cuenta. 
Saludos

**Comment by asanzo** [comment]
Cuídense mucho!!
